"""
Pre-built filter presets refined with Pro-Pop levers and expanded semantic coverage.
"""

import json
from pathlib import Path
from .types import FilterParams

FILTERS: dict[str, FilterParams] = {
    "none": {
        "name": "None",
        "description": "Original image (identity transform)",
        "contrast": 1.0,
        "saturation": 1.0,
        "brightness": 0.0,
        "fade": 0.0,
        "grain": 0.0,
        "temperature": 0.0,
        "vignette": 0.0,
        "highlights": 0.0,
        "shadows": 0.0,
        "vibrance": 0.0,
        "clarity": 0.0,
        "texture": 0.0,
        "dehaze": 0.0,
        "sharpen": 0.0,
    },
    "cinematic": {
        "name": "Cinematic",
        "description": "Teal and orange Hollywood look with professional mid-tone presence",
        "contrast": 1.2,
        "saturation": 0.95,
        "vibrance": 0.2,
        "clarity": 0.15,
        "temperature": -0.02,
        "tint": {"r": 0.05, "g": -0.03, "b": -0.08},
        "shadows": 0.08,
        "highlights": 0.05,
        "vignette": 0.15,
    },
    "glint-raw": {
        "name": "Glint Raw",
        "description": "Gritty micro-detail with a signature faded dynamic range",
        "contrast": 1.25,
        "brightness": -0.05,
        "fade": 0.25,
        "grain": 0.3,
        "clarity": 0.15,
        "texture": 0.2,
        "sharpen": 0.15,
        "highlights": -0.15,
        "shadows": 0.15,
    },
    "portra-400": {
        "name": "Portra 400",
        "description": "Professional portrait film: warm skin tones and soft contrast",
        "contrast": 1.08,
        "saturation": 0.9,
        "vibrance": 0.25,
        "temperature": 0.08,
        "tint": {"r": 0.05, "g": 0.0, "b": -0.02},
        "highlights": -0.05,
        "shadows": 0.1,
        "fade": 0.15,
        "grain": 0.1,
    },
    "gold-200": {
        "name": "Gold 200",
        "description": "Classic warm nostalgia with golden highlights",
        "contrast": 1.15,
        "saturation": 1.05,
        "vibrance": 0.15,
        "temperature": 0.15,
        "tint": {"r": 0.08, "g": 0.05, "b": -0.05},
        "highlights": 0.05,
        "grain": 0.2,
    },
    "velvia-vivid": {
        "name": "Velvia Vivid",
        "description": "High-saturation landscape film with deep greens and sky blues",
        "contrast": 1.3,
        "saturation": 1.2,
        "vibrance": 0.3,
        "dehaze": 0.2,
        "clarity": 0.1,
        "temperature": -0.02,
        "highlights": 0.05,
    },
    "tri-x-pro": {
        "name": "Tri-X Pro",
        "description": "Professional gritty B&W with silver-like highlights",
        "contrast": 1.4,
        "saturation": 0.0,
        "clarity": 0.25,
        "texture": 0.2,
        "sharpen": 0.15,
        "grain": 0.3,
        "vignette": 0.2,
    },
    "cyber-neon": {
        "name": "Cyber Neon",
        "description": "Deep blues and electric pinks for urban night shots",
        "contrast": 1.25,
        "saturation": 0.8,
        "vibrance": 0.4,
        "dehaze": 0.25,
        "texture": 0.2,
        "temperature": -0.15,
        "tint": {"r": 0.1, "g": -0.05, "b": 0.15},
        "shadows": 0.1,
    },
    "dreamcore": {
        "name": "Dreamcore",
        "description": "Liminal, ethereal soft focus with a pastel haze",
        "contrast": 0.85,
        "brightness": 0.05,
        "vibrance": 0.2,
        "fade": 0.35,
        "clarity": -0.3,
        "dehaze": -0.15,
        "temperature": 0.05,
        "grain": 0.15,
    },
    "brutalist": {
        "name": "Brutalist",
        "description": "Cold architectural grit: low saturation, high local contrast",
        "contrast": 1.2,
        "saturation": 0.5,
        "vibrance": -0.2,
        "clarity": 0.35,
        "texture": 0.25,
        "temperature": -0.1,
        "dehaze": 0.1,
    },
    "nordic-cool": {
        "name": "Nordic Cool",
        "description": "Desaturated, blue-shifted landscape with sharp detail",
        "contrast": 1.1,
        "saturation": 0.7,
        "vibrance": -0.1,
        "temperature": -0.2,
        "tint": {"r": -0.05, "g": 0.0, "b": 0.05},
        "clarity": 0.15,
        "texture": 0.1,
        "sharpen": 0.1,
    },
    "forest-fog": {
        "name": "Forest Fog",
        "description": "Volumetric mist and moody greens",
        "contrast": 0.9,
        "saturation": 0.75,
        "vibrance": 0.15,
        "fade": 0.15,
        "dehaze": -0.25,
        "clarity": -0.1,
        "temperature": -0.05,
        "tint": {"r": -0.08, "g": 0.12, "b": -0.03},
        "shadows": 0.1,
        "vignette": 0.25,
    },
    "tokyo-night": {
        "name": "Tokyo Night",
        "description": "Moody city vibes with teal/green tones",
        "contrast": 1.2,
        "saturation": 0.85,
        "vibrance": 0.25,
        "dehaze": 0.15,
        "texture": 0.15,
        "temperature": -0.05,
        "tint": {"r": -0.03, "g": 0.1, "b": 0.12},
        "shadows": 0.1,
    },
    "soft-portrait": {
        "name": "Soft Portrait",
        "description": "Skin-safe vibrance and gentle focus",
        "contrast": 1.05,
        "saturation": 0.9,
        "vibrance": 0.2,
        "clarity": -0.15,
        "highlights": 0.05,
        "shadows": 0.05,
        "temperature": 0.05,
        "fade": 0.1,
    },
    "industrial": {
        "name": "Industrial",
        "description": "Sharp, high-clarity architectural grit",
        "contrast": 1.15,
        "saturation": 0.6,
        "vibrance": -0.1,
        "dehaze": 0.2,
        "clarity": 0.25,
        "texture": 0.2,
        "temperature": -0.1,
        "tint": {"r": -0.05, "g": 0.0, "b": 0.05},
    },
    "high-key": {
        "name": "High Key",
        "description": "Clean, bright, and airy minimalism",
        "contrast": 0.85,
        "brightness": 0.15,
        "saturation": 0.8,
        "vibrance": 0.1,
        "highlights": 0.1,
        "shadows": 0.1,
        "dehaze": -0.05,
        "fade": 0.1,
    },
    "monochrome-pro": {
        "name": "Monochrome Pro",
        "description": "High-presence black and white with deep texture",
        "contrast": 1.3,
        "saturation": 0.0,
        "clarity": 0.25,
        "texture": 0.2,
        "sharpen": 0.15,
        "vignette": 0.2,
    },
    "desert-sun": {
        "name": "Desert Sun",
        "description": "Warm atmospheric clarity and golden tones",
        "contrast": 1.1,
        "brightness": 0.05,
        "vibrance": 0.3,
        "dehaze": 0.1,
        "temperature": 0.15,
        "tint": {"r": 0.08, "g": 0.02, "b": -0.05},
        "highlights": 0.05,
    },
    "clarendon": {
        "name": "Clarendon",
        "description": "Bright, high contrast with cool cyan shadows",
        "contrast": 1.25,
        "saturation": 1.1,
        "vibrance": 0.15,
        "clarity": 0.1,
        "temperature": -0.12,
        "tint": {"r": -0.05, "g": 0.05, "b": 0.08},
        "highlights": 0.1,
        "shadows": 0.05,
    },
    "valencia": {
        "name": "Valencia",
        "description": "Warm vintage fade with creamy yellow tones",
        "contrast": 0.9,
        "saturation": 0.8,
        "vibrance": 0.2,
        "fade": 0.3,
        "temperature": 0.15,
        "tint": {"r": 0.08, "g": 0.05, "b": -0.05},
        "brightness": 0.05,
    },
    "crema": {
        "name": "Crema",
        "description": "Warm vintage matte",
        "contrast": 0.92,
        "saturation": 0.75,
        "vibrance": 0.15,
        "fade": 0.4,
        "temperature": 0.15,
        "brightness": 0.03,
    },
    "juno": {
        "name": "Juno",
        "description": "Teal shadows and warm highlights",
        "contrast": 1.1,
        "saturation": 1.1,
        "temperature": 0.08,
        "tint": {"r": 0.05, "g": -0.05, "b": -0.08},
        "shadows": 0.1,
        "highlights": 0.05,
    },
    "lark": {
        "name": "Lark",
        "description": "Faded, desaturated, misty look",
        "contrast": 0.9,
        "saturation": 0.75,
        "fade": 0.3,
        "brightness": 0.05,
        "temperature": -0.03,
    },
    "gingham": {
        "name": "Gingham",
        "description": "Light, airy, warm brightness",
        "contrast": 0.95,
        "saturation": 0.85,
        "brightness": 0.08,
        "temperature": 0.06,
        "fade": 0.15,
    },
    "moon": {
        "name": "Moon",
        "description": "High contrast black and white",
        "contrast": 1.4,
        "saturation": 0.0,
        "brightness": -0.05,
    },
    "ludwig": {
        "name": "Ludwig",
        "description": "Slightly desaturated with warm shadows",
        "contrast": 1.05,
        "saturation": 0.9,
        "fade": 0.15,
        "temperature": 0.05,
        "tint": {"r": 0.03, "g": 0.0, "b": -0.02},
    },
    "noir": {
        "name": "Noir",
        "description": "Dramatic high contrast black and white",
        "contrast": 1.5,
        "saturation": 0.0,
        "brightness": -0.05,
        "vignette": 0.3,
    },
}


def _load_custom_filters() -> dict[str, FilterParams]:
    """Internal helper to load custom filters from disk."""
    custom_path = Path(__file__).parent.parent / "custom_filters.json"
    if custom_path.exists():
        try:
            with open(custom_path, "r") as f:
                return json.load(f)
        except (json.JSONDecodeError, IOError):
            return {}
    return {}


def list_filters() -> list[tuple[str, str]]:
    """Return list of (name, description) tuples."""
    all_filters = FILTERS.copy()
    custom = _load_custom_filters()
    all_filters.update(custom)
    items = list(all_filters.items())
    return [(k, v.get("description", "")) for k, v in items]


def get_filter(name: str) -> FilterParams | None:
    """Get filter by name, returns None if not found."""
    name_low = name.lower()
    if name_low in FILTERS:
        return FILTERS[name_low]
    custom = _load_custom_filters()
    return custom.get(name_low)
