"""
Pre-built filter presets refined with Pro-Pop levers.
"""

from .types import FilterParams

FILTERS: dict[str, FilterParams] = {
    "none": {
        "name": "None",
        "description": "Original image (identity transform)",
        "contrast": 1.0,
        "saturation": 1.0,
        "brightness": 0.0,
        "fade": 0.0,
        "grain": 0.0,
        "temperature": 0.0,
        "vignette": 0.0,
        "highlights": 0.0,
        "shadows": 0.0,
        "vibrance": 0.0,
        "clarity": 0.0,
        "texture": 0.0,
        "dehaze": 0.0,
        "sharpen": 0.0,
    },
    "cinematic": {
        "name": "Cinematic",
        "description": "Teal and orange Hollywood look with professional mid-tone presence",
        "contrast": 1.2,
        "saturation": 0.95,
        "vibrance": 0.2,
        "clarity": 0.15,
        "temperature": -0.02,
        "tint": {"r": 0.05, "g": -0.03, "b": -0.08},
        "shadows": 0.08,
        "highlights": 0.05,
        "vignette": 0.15,
    },
    "forest-fog": {
        "name": "Forest Fog",
        "description": "Volumetric mist and moody greens",
        "contrast": 0.9,
        "saturation": 0.75,
        "vibrance": 0.15,
        "fade": 0.15,
        "dehaze": -0.25,
        "clarity": -0.1,
        "temperature": -0.05,
        "tint": {"r": -0.08, "g": 0.12, "b": -0.03},
        "shadows": 0.1,
        "vignette": 0.25,
    },
    "glint-raw": {
        "name": "Glint Raw",
        "description": "Gritty micro-detail with a signature faded dynamic range",
        "contrast": 1.25,
        "brightness": -0.05,
        "fade": 0.25,
        "grain": 0.3,
        "clarity": 0.15,
        "texture": 0.2,
        "sharpen": 0.15,
        "highlights": -0.15,
        "shadows": 0.15,
    },
    "tokyo-night": {
        "name": "Tokyo Night",
        "description": "Cyberpunk cityscapes with piercing neon",
        "contrast": 1.2,
        "saturation": 0.85,
        "vibrance": 0.25,
        "dehaze": 0.15,
        "texture": 0.15,
        "temperature": -0.05,
        "tint": {"r": -0.03, "g": 0.1, "b": 0.12},
        "shadows": 0.1,
    },
    "soft-portrait": {
        "name": "Soft Portrait",
        "description": "Skin-safe vibrance and gentle focus",
        "contrast": 1.05,
        "saturation": 0.9,
        "vibrance": 0.2,
        "clarity": -0.15,
        "highlights": 0.05,
        "shadows": 0.05,
        "temperature": 0.05,
        "fade": 0.1,
    },
    "industrial": {
        "name": "Industrial",
        "description": "Cold, sharp, and high-clarity architectural grit",
        "contrast": 1.15,
        "saturation": 0.6,
        "vibrance": -0.1,
        "dehaze": 0.2,
        "clarity": 0.25,
        "texture": 0.2,
        "temperature": -0.1,
        "tint": {"r": -0.05, "g": 0.0, "b": 0.05},
    },
    "high-key": {
        "name": "High Key",
        "description": "Clean, bright, and airy minimalism",
        "contrast": 0.85,
        "brightness": 0.15,
        "saturation": 0.8,
        "vibrance": 0.1,
        "highlights": 0.1,
        "shadows": 0.1,
        "dehaze": -0.05,
        "fade": 0.1,
    },
    "monochrome-pro": {
        "name": "Monochrome Pro",
        "description": "High-presence black and white with deep texture",
        "contrast": 1.3,
        "saturation": 0.0,
        "clarity": 0.25,
        "texture": 0.2,
        "sharpen": 0.15,
        "vignette": 0.2,
    },
    "desert-sun": {
        "name": "Desert Sun",
        "description": "Warm atmospheric clarity and golden tones",
        "contrast": 1.1,
        "brightness": 0.05,
        "vibrance": 0.3,
        "dehaze": 0.1,
        "temperature": 0.15,
        "tint": {"r": 0.08, "g": 0.02, "b": -0.05},
        "highlights": 0.05,
    },
    "clarendon": {
        "name": "Clarendon",
        "description": "Bright, high contrast with cool cyan shadows",
        "contrast": 1.25,
        "saturation": 1.1,
        "vibrance": 0.15,
        "clarity": 0.1,
        "temperature": -0.12,
        "tint": {"r": -0.05, "g": 0.05, "b": 0.08},
        "highlights": 0.1,
        "shadows": 0.05,
    },
    "valencia": {
        "name": "Valencia",
        "description": "Warm vintage fade with creamy yellow tones",
        "contrast": 0.9,
        "saturation": 0.8,
        "vibrance": 0.2,
        "fade": 0.3,
        "temperature": 0.15,
        "tint": {"r": 0.08, "g": 0.05, "b": -0.05},
        "brightness": 0.05,
    },
    "crema": {
        "name": "Crema",
        "description": "Warm vintage matte",
        "contrast": 0.92,
        "saturation": 0.75,
        "vibrance": 0.15,
        "fade": 0.4,
        "temperature": 0.15,
        "brightness": 0.03,
    },
}


def list_filters() -> list[tuple[str, str]]:
    """Return list of (name, description) tuples."""
    items = list(FILTERS.items())
    return [(k, v.get("description", "")) for k, v in items]


def get_filter(name: str) -> FilterParams | None:
    """Get filter by name, returns None if not found."""
    return FILTERS.get(name.lower())
